[package]
name = "currency_api"
version = "0.1.0"
authors = ["dutchmartin <martijn.groeneveldt@gmail.com>"]
edition = "2018"

[dependencies]
azure-functions = "0.6.0"
serde = {version = "1.0.89", features = ["derive"]}
serde_json = "1.0.39"